config/routes.rb
MapShare::Application.routes.draw do
  devise_for :users

    root :to => 'home#index'

    resources :maps
    post 'maps/merge' => 'maps#merge'

    resources :places
    resources :places do
      post 'add', on: :member
    end

    resources :requests
    resources :requests do
      post 'copy', on: :member
      post 'allow', on: :member
    end

    post 'requests/ask_for_map' => 'requests#ask_for_map'
    

end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
  has_many :map_memberships
  #has_many :places
  has_many :places, through: :map_memberships

  geocoded_by :city, :latitude  => :center_lat, :longitude => :center_lng
  after_validation :geocode

  # remove bandmembership linking self, place
  # make a copy of place and add it to self.places
  def adjust_place(place, place_attrs)
    MapMembership.where(map_id: self.id, place_id: place.id).delete_all
    self.places << Place.create(place_attrs)
  end

  def add_place(place)
    
    place_copy = Place.create(
      title: place.title,
      address: place.address,
      link: place.link,
      description: place.description
      )
    self.places << place_copy
  end

  # adds map1's places to self
  def merge(map1)
    unless self == map1
      self.places += map1.places
    end

  end
end

app/models/map_membership.rb
class MapMembership < ActiveRecord::Base
  belongs_to :map
  belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :map_memberships
  has_many :maps, through: :map_memberships

  geocoded_by :address, :latitude  => :lat, :longitude => :lng
  after_validation :geocode
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #attr_accessible :email, :password, :password_confirmation
  has_many :maps
  has_many :requests

  def add_map_copy(map)
    map_copy = Map.create(
      title: map.title,
      city: map.city,
      user_id: self.id,
      places: map.places
    )
  # seems to have uninteded consequence of deleting
  # the places from map... though only in browser not in rails console
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @map = Map.new
		@users = User.all
	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@maps = Map.all
	end

	def create
		map = Map.create(map_params)
		redirect_to edit_map_path(map)
	end

	def show
		@map = Map.find(params[:id])
		@places = @map.places
		@hash = 
			Gmaps4rails.build_markers(@places) do |place, marker|
  			marker.lat place.lat
  			marker.lng place.lng
  			marker.infowindow("#{place.title}: #{place.description}")
			end
	end

	def edit
		@map = Map.find(params[:id])
		if current_user != @map.user
			flash[:notice] = "You can't edit this map if you aren't the owner"
			redirect_to map_path(@map)  	
	  end
	  @place = Place.new
	  @places = @map.places
	  if @map.places.any?
			@hash = 
				Gmaps4rails.build_markers(@places) do |place, marker|
	  			marker.lat place.lat
	  			marker.lng place.lng
	  			marker.infowindow("#{place.title}: #{place.description}")
				end
		else
			@hash = []
		end

	end

	def update
		map = Map.find(params[:id])
		map.title = params[:map][:title]
		map.save
		redirect_to root_path
	end

	def destroy
		Map.find(params[:id]).delete
		redirect_to root_path
	end

	def merge
		map1 = Map.find(params[:map1][:id])
		map2 = Map.find(params[:map2][:id])
		map2.merge(map1)
		flash[:notice] = "#{map1.title} successfully merged into #{map2.title}!"
		redirect_to root_path
	end

end

private
  def map_params
    params.require('map').permit(:title, :city, :user_id)
  end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def create
    place = Place.create(place_params)
    map_id = params[:place][:map_id]
    map = Map.find(map_id)
    MapMembership.create(map_id: map_id, place_id: place.id)
    redirect_to edit_map_path(map)
  end

  def edit
    @place = Place.find(params[:id])
    @map_id = params[:map_id]
  end

  # not quite an accurate name
  def update
    place = Place.find(params[:id])
    map = Map.find(params[:map_id])
    #place.update(place_params)
    place_attrs = place_params
    #binding.pry
    map.adjust_place(place, place_attrs)
    redirect_to edit_map_path(map)
  end

  def destroy
    map = Map.find(params[:place][:map_id])
    MapMembership.where(place_id: params[:id], map_id: map.id).delete_all
    redirect_to edit_map_path(map)
  end

  def add
    place = Place.find(params[:place][:place_id])
    map = Map.find(params[:map][:id])
    map.add_place(place)
    flash[:notice] = "#{place.title} added to #{map.title}"
    redirect_to map_path
  end

end

private
  def place_params
    params.require('place').permit(:title, :address, :link, :description)
  end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
    req = Request.create(
      map_id: params[:map][:id],
      from_user: current_user.id,
      # user_id: receiving user's id
      user_id: params[:user][:id],
      verb: "share"
    )
    
    flash[:notice] = "Map sent to #{User.find(req.user_id).email} successfully!"
    redirect_to root_path
  end

  def destroy
    Request.find(params[:id]).delete
    redirect_to root_path
  end

  def copy
    req = Request.find(params[:id])
    map = Map.find(req.map_id)
    current_user.add_map_copy(map)
    req.delete
    redirect_to root_path
  end

  def ask_for_map
    map = Map.find(params[:map_id])
    Request.create(
      map_id: map.id,
      from_user: current_user.id,
      user_id: map.user_id,
      verb: "follow"
    )
    flash[:notice] = "Map requested!"
    redirect_to maps_path
  end

  def allow
    #binding.pry
    req = Request.find(params[:id])
    user = User.find(req.from_user)
    map = Map.find(req.map_id)
    # change this to actually allow following?
    user.add_map_copy(map)
    req.delete
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<h1>Mapshare</h1>
<%= link_to "See all  maps", maps_path %>

<% if user_signed_in? %>

  <!-- Current Requests -->
  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Inbox (<%= current_user.requests.count %> new)</h3></div>
    <table class="table table-condensed">
      <% current_user.requests.each do |req| %>
        <% if req.verb == "share" %>
          <tr>
            <% map = Map.find(req.map_id) %>
            <td><%= User.find(req.from_user).email %> wants to share <%= link_to "#{map.title} (#{map.city})", map_path(map) %></td>
            <td align="center"><%= button_to 'accept', copy_request_path(req), method: :post, class: "btn btn-primary btn-xs" %></td>
            <td align="right"><%= button_to "delete", req, method: :delete, class: "btn btn-danger btn-xs" %></td>
          </tr>
        <% elsif req.verb == "follow" %>
          <tr>
            <% map = Map.find(req.map_id) %>
            <td><%= User.find(req.from_user).email %> wants to follow your map <%= link_to map.title, map_path(map) %></td>
            <td align="center"><%= button_to "allow", allow_request_path(req), method: :post, class: "btn btn-primary btn-xs" %></td>
            <td align="right"><%= button_to "delete", req, method: :delete, class: "btn btn-danger btn-xs" %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>


  <!-- User's Maps -->
  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Your Maps</h3></div>
    <table class="table table-hover">
      <tbody>
      <% current_user.maps.each do |map| %>
        <tr>
          <td><%= link_to(map.title, map_path(map)) %></td>
          <td><%= map.city %></td>
          <td><%= link_to("edit", edit_map_path(map)) %></td> 
          <td align="right"><%= button_to "delete", map, method: :delete, class: "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>


  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title">Actions</h3></div>
    <table class="table">
      <tbody>
        <tr>
          <td align="center"><h5>New Map</h5></td>
          <%= form_for @map, html: {class: "form-inline", role: "form"} do |f| %>
          <td>
            <%= f.label :title, class: "sr-only" %>
            <%= f.text_field :title, class: "form-control input-sm", placeholder: "Title" %>  
          </td>
          <td></td>
          <td>
            <%= f.label :city, class: "sr-only" %>
            <%= f.text_field :city, class: "form-control input-sm", placeholder: "City, State" %>
            <%= f.hidden_field :user_id, value: current_user.id %>
          </td>
          <td align="center">
            <%= f.submit "Create Map", class: "btn btn-primary btn-sm" %>
          </td>
          <% end %>
        </tr>

        <tr>
          <td align="center"><h5>Merge</h5></td>
          <%= form_tag maps_merge_path, class: 'form-inline' do %>
          <td>
            <%= collection_select(:map1, :id, current_user.maps, :id, :title, {}, {class: 'form-control input-sm'}) %>
          </td>
          <td align="center"><h5>into</h5></td>
          <td>
            <%= collection_select(:map2, :id, current_user.maps, :id, :title, {}, {class: 'form-control input-sm'}) %>
          </td>
          <td align="center">
            <%= submit_tag("Merge", class: "btn btn-primary btn-sm") %>
          </td>
          <% end %> 
        </tr>

        <tr>
          <td align="center"><h5>Send</h5></td>
          <%= form_tag({controller: "requests", action: "create"}, method: "post", class: "form-inline") do %>
          <td>
            <%= collection_select(:map, :id, current_user.maps, :id, :title, {}, {class: 'form-control input-sm'}) %>
          </td>
          <td align="center"><h5>to</h5></td>
          <td>
            <%= collection_select(:user, :id, User.all, :id, :email, {}, {class: 'form-control input-sm'}) %>
          </td>
          <td align="center">
            <%= submit_tag("Send Map", class: "btn btn-primary btn-sm") %>
          </td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MapShare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "gmaps4rails" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

</head>
<body>
  <div class="container">
	<%= notice %>
  <%= alert %>

	<div>
		<% if user_signed_in? %>
			Signed in as <%= current_user.email %> 
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
      <%= link_to "home", root_path %>
		<% else %>
			<%= link_to "sign in", new_user_session_path %>
			<%= link_to "sign up", new_user_registration_path %>
		<% end %>
	</div>

  
  
	  <%= yield %>
  </div>

</body>
</html>

app/views/maps/edit.html.erb
<script type="text/javascript">
  setTimeout(
  window.onload = function() {
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {zoom: 13}, internal: {id: 'map'} }, 
      function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.map.centerOn({ lat: <%=@map.center_lat%>, lng: <%=@map.center_lng%> });
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();     
      });
  }, 1)
</script>

<h1>Edit Map: <%= "#{@map.title} (#{@map.city})" %></h1>
<%= link_to "finished", root_path %>

<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title">Places (<%= @map.places.count %>)</h3></div>
  <table class="table table-condensed">
    <% @map.places.each do |place| %>
      <tr>
        <td><%= place.title %></td>
        <td><%= place.address %></td>
        <td><%= link_to place.link, place.link, target: "_blank" %></td>
        <td><%= place.description %></td>
        <td>
          <%= form_tag edit_place_path(place), method: :get do  %>
            <%= hidden_field_tag :map_id, @map.id %>
            <%= submit_tag "edit", class: "btn btn-primary btn-xs" %>
          <% end %>
        </td>
        <td align="right">
          <%= form_for place do |f| %>
            <%= f.hidden_field :map_id, value: @map.id %>
            <%= button_to "remove", place, method: :delete, class: "btn btn-danger btn-xs" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div class="navbar-form" align="center" style="margin-top: -10px">
<%= form_for @place, html: {class: "form-inline"} do |f| %>
  <div class="form-group has-info">
    <%= f.label :title, class: "sr-only" %>
    <%= f.text_field :title, class: "form-control input-sm", placeholder: "title" %>
  </div>
  <div class="form-group has-info">
    <%= f.label :address, class: "sr-only" %>
    <%= f.text_field :address, class: "form-control input-sm", placeholder: "address or landmark" %>
  </div>
  <div class="form-group has-info">
    <%= f.label :link, class: "sr-only" %>
    <%= f.text_field :link, class: "form-control input-sm", placeholder: "url (optional)" %>
  </div>
  <div class="form-group has-info">
    <%= f.label :description, class: "sr-only" %>
    <%= f.text_field :description, class: "form-control input-sm", placeholder: "description (optional)" %>
  </div>
  <%= f.hidden_field :map_id, value: @map.id %>
  <%= f.submit "Add Place", id: "submit", class: "btn btn-success btn-sm" %>
<% end %>
</div>
<div class="panel panel-success">
  <div class="panel-body" id="map" style="height: 600px"></div>
</div>

app/views/maps/index.html.erb
<h1>All Maps</h1>

<div class="panel panel-default">
  <div class="panel-heading"><h2 class="panel-title">All Public Maps (<%= @maps.count %>)</h2></div>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>City</th>
        <th>Owner</th>
      </tr>
    </thead>
    <tbody>
  <% @maps.each do |map| %>
    <tr>
      <td><%= link_to(map.title, map_path(map)) %></td>
      <td><%= map.city %></td>
      <td><%= User.find(map.user_id).email %></td> 
      <td align="right">
        <%= form_tag({controller: "requests", action: "ask_for_map"}, method: "post", class: "") do %>
          <%= hidden_field_tag :map_id, map.id %>
          <%= submit_tag "Request this Map", class: "btn btn-primary btn-sm" %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

app/views/maps/show.html.erb
<script type="text/javascript">
  setTimeout(
  window.onload = function() {
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });
  }, 1)
</script>

<h1><%= "#{@map.title} (#{@map.city})" %></h1>
<%= link_to "edit map", edit_map_path(@map) %>

<div class="panel panel-default">
  <div class="panel-heading"><h3 class="panel-title">Places (<%= @map.places.count %>)</h3></div>
  <table class="table table-condensed table-condensed">
    <% @map.places.each do |place| %>
      <tr>
        <td><%= place.title %></td>
        <td><%= place.address %></td>
        <td><%= link_to place.link, place.link, target: "_blank" %></td>
        <td><%= place.description %></td>
        <td align="right">
          <%= form_for place, url: add_place_path, method: :post, html: {class: "form-inline", role: "form"} do |f| %>
            <%= f.hidden_field :place_id, value: place.id %>
            <%= f.submit "Add to", class: "btn btn-primary btn-xs" %>
            <%= collection_select(:map, :id, current_user.maps, :id, :title, {}, {class: ''}) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<div class="panel panel-success">
  <div class="panel-body" id="map" style="height: 600px"></div>
</div>

app/views/places/edit.html.erb
<%= form_for @place do |f| %>
  <%= f.text_field :title, placeholder: "Title" %>
  <%= f.text_field :address, placeholder: "Address or landmark" %>
  <%= f.text_field :link, placeholder: "url (optional)" %>
  <%= f.text_field :description, placeholder: "description (optional)" %>
  <%= hidden_field_tag :map_id, @map_id %>
  <%= f.submit "Update Place", id: "submit" %>
<% end %>